const SET_LOGIN_VALUE = "SET_LOGIN_VALUE";
const SET_PASSWORD_VALUE = "SET_PASSWORD_VALUE";
const SET_IS_VALIDATION_STATUS = "SET_IS_VALIDATION_STATUS";
const SET_IS_VALID_LOGIN = "SET_IS_VALID_LOGIN";
const SET_IS_VALID_PASSWORD = "SET_IS_VALID_PASSWORD";
const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
const SET_CURRENT_USER = "SET_CURRENT_USER";

const REDUCER_TYPES = {
  SET_LOGIN_VALUE,
  SET_PASSWORD_VALUE,
  SET_IS_VALIDATION_STATUS,
  SET_IS_VALID_LOGIN,
  SET_IS_VALID_PASSWORD,
  SET_LOGIN_STATUS,
  SET_CURRENT_USER
};

export default REDUCER_TYPES;
