const SET_LOGIN_VALUE = "SET_LOGIN_VALUE";
const SET_PASSWORD_VALUE = "SET_PASSWORD_VALUE";
const SET_IS_VALIDATION_STATUS = "SET_IS_VALIDATION_STATUS";
const SET_IS_VALID_LOGIN = "SET_IS_VALID_LOGIN";
const SET_IS_VALID_PASSWORD = "SET_IS_VALID_PASSWORD";

const REDUCER_TYPES = {
  SET_LOGIN_VALUE,
  SET_PASSWORD_VALUE,
  SET_IS_VALIDATION_STATUS,
  SET_IS_VALID_LOGIN,
  SET_IS_VALID_PASSWORD,
};

export default REDUCER_TYPES;
