const SET_CURRENT_SEARCH_VALUE = "SET_CURRENT_SEARCH_VALUE";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_LOADING_STATUS = "SET_LOADING_STATUS";
const SET_CURRENT_VIEWABLE_RECIPES = "SET_CURRENT_VIEWABLE_RECIPES";
const SET_TITLE_NEW_RECIPE = "SET_TITLE_NEW_RECIPE";
const SET_DESCRIPTION_NEW_RECIPE = "SET_DESCRIPTION_NEW_RECIPE";

const REDUCER_TYPES = {
  SET_CURRENT_SEARCH_VALUE,
  SET_CURRENT_PAGE,
  SET_LOADING_STATUS,
  SET_CURRENT_VIEWABLE_RECIPES,
  SET_TITLE_NEW_RECIPE,
  SET_DESCRIPTION_NEW_RECIPE
};

export default REDUCER_TYPES;
